name: CI-docker-image 

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:
    
jobs:
  docker:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
     
    - name: Set up QEMU
      uses: action/setup-qemu-action@v1

    - name: Login to DockerHub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secret.DOCKER_USERNAME }}
        password: ${{ secret.DOCKER_TOKEN }}

 
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: . 
        file: ./Dockerfile
        push: true
        tags: ${{ secret.DOCKER_USERNAME }}/sample:latest, ${{ secret.DOCKER_USERNAME }}/sample:${{ github.run_number }}
